import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds a complete self-contained S3 page", async () => {
  const html = await readFile(new URL("../dist/celebrating-sixty.html", import.meta.url), "utf8");

  assert.match(html, /Five beautiful ways/);
  assert.match(html, /Calimac Productions/);
  assert.match(html, /celebrate the beautiful person you are/);
  assert.match(html, /For Diane with all my love\./);
  assert.doesNotMatch(html, /beautiful, extraordinary life you’ve created/);
  assert.match(html, /Casa Suhana/);
  assert.match(html, /Casa Rayrae/);
  assert.match(html, /Flora Farms/);
  assert.doesNotMatch(html, /Manava Overwater/);
  assert.doesNotMatch(html, /Hale Naiʻa/);
  assert.match(html, /id="puerto-vallarta"/);
  assert.match(html, /All destinations/);
  assert.match(html, /Sixty is a special birthday/);
  assert.match(html, /That part belongs to you/);
  assert.match(html, /only the one that feels right/);
  assert.doesNotMatch(html, /feels most like us/);
  assert.match(html, /id="start"/);
  assert.match(html, /class="header-dedication" href="#">For Diane<\/a>/);
  assert.match(html, /class="more-chapter" href="#">Explore two more possibilities<\/a>/);
  assert.match(html, /class="book-it" href="#">Book one of these<\/a>/);
  assert.match(html, /22–29 October · Seven nights/);
  assert.match(html, /15–22 October · Seven nights/);
  assert.match(html, /21–27 October · Six nights/);
  assert.match(html, /21–28 October · Seven nights/);
  assert.match(html, /data:image\/(?:jpeg|webp);base64,/);
  assert.doesNotMatch(html, /<script\b/i);
  assert.doesNotMatch(html, /(?:src|href)="\//i);
  assert.doesNotMatch(html, /http:\/\/localhost/i);
});

test("builds a private, self-contained More Possibilities chapter", async () => {
  const html = await readFile(new URL("../dist/more/index.html", import.meta.url), "utf8");
  assert.match(html, /One more thing/);
  assert.match(html, /It’s going somewhere together/);
  assert.match(html, /Montecristo Estates/);
  assert.match(html, /15–22 October · 7 nights/);
  assert.match(html, /22–29 October · 7 nights/);
  assert.match(html, /Puerto Vallarta/);
  assert.doesNotMatch(html, /Waikoloa Beach Villas/);
  assert.match(html, /So… where to/);
  assert.match(html, /class="more-book-it" href="#">Book it<\/a>/);
  assert.doesNotMatch(html, /\$6K|budget|fallback|control plane|price confidence/i);
  assert.match(html, /data:image\/(?:jpeg|webp);base64,/);
  assert.doesNotMatch(html, /<script\b/i);
  assert.doesNotMatch(html, /(?:src|href)="\//i);
});

test("builds both planning collections in one continuous dashboard", async () => {
  const html = await readFile(new URL("../dist/control/index.html", import.meta.url), "utf8");
  assert.match(html, /Original Experience/);
  assert.match(html, /Casa Suhana/);
  assert.match(html, /Casa Rayrae/);
  assert.doesNotMatch(html, /Hale Naiʻa/);
  assert.match(html, /The Lagoon House/);
  assert.doesNotMatch(html, /Manava Moʻorea · Overwater Bungalow/);
  assert.match(html, /More Possibilities/);
  assert.match(html, /\$7,000–\$8,000/);
  assert.match(html, /October 15–22/);
  assert.match(html, /\$2,550–\$6,666/);
  assert.match(html, /Estimated total range/);
  assert.match(html, /Nonrefundable · \$1,852/);
  assert.match(html, /Before tax · \$2,198/);
  assert.match(html, /\$1,852–\$2,198/);
  assert.match(html, /Trip planner/);
  assert.match(html, /Budget variance/);
  assert.match(html, /La Puesta Sayulita/);
  assert.doesNotMatch(html, /Rivera del Rio/);
  assert.doesNotMatch(html, /Casa Velas/);
  assert.match(html, /Room-only lodging rates are required/);
  assert.match(html, /Needs refresh/);
  assert.match(html, /Needs verification/);
  assert.match(html, /Verified prices are shown individually/);
  assert.match(html, /Previous valid total/);
  assert.match(html, />Flights</);
  assert.match(html, /Planned-date airfare · included in cost breakdown/);
  assert.match(html, /Lower flexible-date alternative/);
  assert.match(html, /Two travelers · matches cost breakdown/);
  assert.match(html, /<dt>Airfare<\/dt><dd>\$2,621<\/dd>/);
  assert.match(html, /included in cost breakdown · two travelers<\/span><strong>\$2,621/);
  assert.match(html, /<dt>Airfare<\/dt><dd>\$2,144<\/dd>/);
  assert.match(html, /included in cost breakdown · two travelers<\/span><strong>\$2,144/);
  assert.match(html, /Last lodging check/);
  assert.match(html, /Google Flights via SerpApi/);
  assert.match(html, /vegan/i);
  assert.match(html, /Last refreshed/);
  assert.equal((html.match(/Last refreshed/g) ?? []).length, 1);
  assert.match(html, /aria-label="Planning collections"/);
  assert.match(html, /id="collection-extraordinary"/);
  assert.match(html, /id="collection-beautiful-week"/);
  assert.match(html, /View details/);
  assert.doesNotMatch(html, /Attention needed|Needs Attention/);
  assert.match(html, /Pricing monitored/);
  assert.match(html, /\.control-shell h1,[^{]+\{[^}]*font-family:inherit/);
  assert.doesNotMatch(html, /island hop/);
  assert.doesNotMatch(html, /Cabo Surf Hotel|Grand Miramar|Pueblo Bonito Pacifica|Pueblo Bonito Sunset Beach|Waikoloa Beach Marriott Resort &amp; Spa/);
  assert.doesNotMatch(html, /<script\b/i);
});
