import type { CollectionViewModel, DestinationViewModel, StatusKind } from "./control-model";

const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const statusLabels:Record<StatusKind,string>={current:"Current",estimated:"Estimated",verify:"Needs verification",stale:"Needs refresh",unavailable:"Unavailable"};
function formatDateTime(value:string|null){return value?new Date(value).toLocaleString("en-US",{timeZone:"America/Los_Angeles",month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}):"Awaiting first check"}
function formatDates(value:string){const[start,end]=value.split("/");if(!start||!end)return value;const date=(item:string)=>new Date(`${item}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric"});return `${date(start)}–${date(end)}, ${end.slice(0,4)}`}
function formatBudgetVariance(destination:DestinationViewModel){const range=destination.budgetVarianceRange;if(!range){const positive=destination.budgetVariance>=0;return {value:`${money.format(Math.abs(destination.budgetVariance))} ${positive?"under":"over"}`,tone:positive?"positive" as const:"negative" as const};}if(range.min>=0)return {value:`${money.format(range.min)}–${money.format(range.max)} under`,tone:"positive" as const};if(range.max<=0)return {value:`${money.format(Math.abs(range.max))}–${money.format(Math.abs(range.min))} over`,tone:"negative" as const};return {value:`${money.format(Math.abs(range.min))} over–${money.format(range.max)} under`,tone:"default" as const};}
function StatusChip({status,label}:{status:StatusKind;label?:string}){return <span className={`cp-status-chip cp-status-${status}`}>{label??statusLabels[status]}</span>}
function Metric({label,value,supporting,tone="default"}:{label:string;value:string;supporting?:string;tone?:"default"|"positive"|"negative"}){return <div className={`cp-metric cp-metric-${tone}`}><span>{label}</span><strong>{value}</strong>{supporting&&<small>{supporting}</small>}</div>}
function CostBreakdown({destination}:{destination:DestinationViewModel}){const labels:Array<[keyof DestinationViewModel["costs"],string]>=[["lodging","Lodging"],["airfare","Airfare"],["transport","Local transport"],["meals","Meals"],["experiences","Experiences"],["contingency","Contingency"]];return <dl className="cp-cost-breakdown">{labels.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{key==="lodging"&&destination.lodgingRange?`${money.format(destination.lodgingRange.min)}–${money.format(destination.lodgingRange.max)}`:money.format(destination.costs[key])}</dd></div>)}</dl>}
function DestinationDetails({destination}:{destination:DestinationViewModel}){return <div className="cp-destination-details">
  <section aria-labelledby={`${destination.id}-costs`}><h4 id={`${destination.id}-costs`}>Cost breakdown</h4><CostBreakdown destination={destination}/></section>
  <div className="cp-detail-columns"><section aria-labelledby={`${destination.id}-monitoring`}><h4 id={`${destination.id}-monitoring`}>Monitoring</h4><p>{destination.monitoring.summary}</p><dl className="cp-fact-list"><div><dt>Availability</dt><dd>{destination.availability}</dd></div><div><dt>Refundability</dt><dd>{destination.refundability}</dd></div><div><dt>Previous valid total</dt><dd>{destination.monitoring.previousTotal===null?"First check":money.format(destination.monitoring.previousTotal)}</dd></div></dl></section>
  <section aria-labelledby={`${destination.id}-flights`}><h4 id={`${destination.id}-flights`}>Flights</h4>{destination.flight&&<p><strong>{destination.flight.origin} → {destination.flight.destination}</strong><br/>{destination.flight.cabin}</p>}{destination.plannedFare?<div className="cp-live-fare"><span>Planned-date airfare · included in cost breakdown · two travelers</span><strong>{money.format(destination.plannedFare.price)} · {destination.plannedFare.airline}</strong><p>{destination.plannedFare.origin} → {destination.plannedFare.destination} · {destination.plannedFare.cabin}<br/>{destination.plannedFare.outboundDate}–{destination.plannedFare.returnDate}<br/>{destination.plannedFare.flights}</p><small>{destination.plannedFare.source}</small></div>:<p>No qualifying planned-date itinerary returned.</p>}{destination.liveFare&&destination.liveFare.shift!==0&&<div className="cp-live-fare"><span>{destination.liveFare.status==="stale"?"Prior flexible-date alternative · refresh failed":"Lower flexible-date alternative"} · not included in cost breakdown</span><strong>{money.format(destination.liveFare.price)} · {destination.liveFare.airline}</strong><p>{destination.liveFare.origin} → {destination.liveFare.destination} · {destination.liveFare.cabin}<br/>{destination.liveFare.outboundDate}–{destination.liveFare.returnDate}<br/>{destination.liveFare.flights}</p><small>{destination.liveFare.source}</small></div>}</section></div>
  {destination.properties.length>0&&<section aria-labelledby={`${destination.id}-properties`}><h4 id={`${destination.id}-properties`}>Properties to monitor</h4><div className="cp-property-list">{destination.properties.map((property)=>{const status=property.alternativeQuote?"verify":property.lodgingPrice?.status??property.confidence;const unavailableLabel=property.lodgingPrice?.availability===false?"Unavailable for dates":"Price not found";return <article key={property.name}><div><a href={property.source} target="_blank" rel="noreferrer">{property.name}</a><p>{property.role} · {property.inventory}</p></div>{!property.alternativeQuote&&<StatusChip status={status} label={status==="unavailable"?unavailableLabel:undefined}/>} {property.alternativeQuote&&<p><strong>{money.format(property.alternativeQuote.total)} total</strong> · {property.alternativeQuote.dates}<br/><small>{property.alternativeQuote.detail}</small></p>}{property.lodgingPrice?.total&&<p><strong>{money.format(property.lodgingPrice.total)} total</strong>{property.lodgingPrice.nightly?` · ${money.format(property.lodgingPrice.nightly)}/night`:""} · {property.lodgingPrice.source}<br/><small>{property.lodgingPrice.room?`${property.lodgingPrice.room} · `:""}{property.lodgingPrice.refundable===true?"Refundable":property.lodgingPrice.refundable===false?"Nonrefundable":"Refundability not provided"} · {property.lodgingPrice.official?"direct":"third party"} · checked {formatDateTime(property.lodgingPrice.checkedAt)}</small></p>}{property.lodgingPrice?.reason&&!property.alternativeQuote&&<p>{property.lodgingPrice.reason}</p>}<p>{property.note}</p><small>{property.vegan}</small></article>})}</div></section>}
  {destination.note&&<section><h4>Planning note</h4><p>{destination.note}</p></section>}
  <div className="cp-detail-columns compact"><section><h4>Dining</h4><ul>{destination.dining.map((item)=><li key={item}>{item}</li>)}</ul></section><section><h4>Experiences</h4>{destination.experiences.length?<ul>{destination.experiences.map((item)=><li key={item}>{item}</li>)}</ul>:<p>No separate experience assumptions recorded.</p>}</section></div>
  {destination.source&&<a className="cp-text-link" href={destination.source} target="_blank" rel="noreferrer">Open primary source</a>}
 </div>}
function DestinationCard({destination}:{destination:DestinationViewModel}){const variance=formatBudgetVariance(destination);const statusLabel=destination.confidence==="unavailable"&&destination.availability.startsWith("Unavailable")?"Unavailable for dates":undefined;const pricedLodgingCount=destination.properties.filter((property)=>property.alternativeQuote||property.lodgingPrice?.total).length;return <article className="cp-destination-card" id={`destination-${destination.collectionId}-${destination.id}`}><header><div><p>{destination.destination}</p><h3>{destination.name}</h3><span>{formatDates(destination.dates)}</span></div><StatusChip status={destination.confidence} label={statusLabel}/></header>
  <div className="cp-summary-metrics"><Metric label={destination.budgetVarianceRange?"Budget variance range":"Budget variance"} value={variance.value} supporting={destination.budgetVarianceRange?`Across ${pricedLodgingCount} displayed lodging quotes`:undefined} tone={variance.tone}/><Metric label={destination.totalRange?"Estimated total range":"Estimated total"} value={destination.totalRange?`${money.format(destination.totalRange.min)}–${money.format(destination.totalRange.max)}`:money.format(destination.total)} supporting={destination.totalRange?`Across ${pricedLodgingCount} listed lodging options; uses planned-date airfare`:"Uses planned-date airfare"}/><Metric label="Planned-date airfare" value={destination.plannedFare?money.format(destination.plannedFare.price):"Not available"} supporting={destination.plannedFare?"Two travelers · matches cost breakdown":undefined}/></div>
  <dl className="cp-summary-facts"><div><dt>Availability</dt><dd>{destination.availability}</dd></div><div><dt>Refundability</dt><dd>{destination.refundability}</dd></div><div><dt>Last lodging check</dt><dd>{formatDateTime(destination.monitoring.checkedAt)}</dd></div></dl>
  <details><summary>View details</summary><DestinationDetails destination={destination}/></details></article>}

export default function ControlDashboard({collections,checkedAt,source,nextCheck}:{collections:CollectionViewModel[];checkedAt:string|null;source:string;nextCheck:string}){
 return <main className="control-shell"><header className="cp-app-bar"><div><span className="cp-eyebrow">Calimac Productions</span><h1>Trip planner</h1><p>Diane’s 60th birthday · Private planning dashboard</p></div><span className="cp-privacy-label">Private · Ian only</span></header>
  <section className="cp-refresh-row" aria-label="Pricing status"><div><span>Last refreshed</span><strong>{formatDateTime(checkedAt)}</strong></div><div><span>Next check</span><strong>{nextCheck}</strong></div><div className="cp-refresh-state"><span className="cp-state-dot" aria-hidden="true"/><strong>Pricing monitored</strong></div><small>{source}</small></section>
  <nav className="cp-collection-tabs" aria-label="Planning collections">{collections.map((item)=><a key={item.id} href={`#collection-${item.id}`}>{item.label}<span>{item.targetLabel}</span></a>)}</nav>
  {collections.map((collection)=> <section id={`collection-${collection.id}`} className={`cp-collection-panel cp-panel-${collection.id}`} aria-labelledby={`heading-${collection.id}`} key={collection.id}><header className="cp-collection-summary"><div><span className="cp-eyebrow">Selected collection</span><h2 id={`heading-${collection.id}`}>{collection.label}</h2></div><p>{collection.description}</p></header>
   <div className="cp-destination-grid">{collection.destinations.map((destination)=><DestinationCard destination={destination} key={destination.id}/>)}</div></section>)}
 </main>}
